### ISSUE TITLE
Example Application in the cloud do not work

### ISSUE THREAD

**Issue by kaizokun** [joinfaces/joinfaces-maven-jar-example#219]
https://joinfaces-example.herokuapp.com/index.jsf 

`Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Fri Aug 03 09:38:54 UTC 2018
There was an unexpected error (type=Internal Server Error, status=500).
javax/servlet/jsp/jstl/core/Config`

**Comment by persapiens** [comment]
Hi @kaizokun ,

    Thanks for reporting.
    It is back. I did nothing. It run with limited resources (free heroku account).
    You are welcome.

**Comment by kaizokun** [comment]
All right, anyway I've been able to use that very convenient tool localy to generate the pom for Primefaces.
thanks for the initiative !

**Comment by melloware** [comment]
I think this is related to this which I just fixed: https://github.com/joinfaces/joinfaces-maven-jar-example/issues/269

**Comment by persapiens** [comment]
hi @kaizokun and @melloware 

Just point your browser to https://joinfaces-example.herokuapp.com

I think #271 is not necessary.

**Comment by melloware** [comment]
OHH then your github page is wrong it says navigate to index.jsf both for local host and the URL for the Heroku app
