### ISSUE TITLE
Session Bean

### ISSUE THREAD

**Issue by edeani** [joinfaces/joinfaces-maven-jar-example#323]
Do you have an example with session bean? I wat to use joinfaces with session bean component.

**Comment by TownCube** [comment]
All [the usual session](https://docs.joinfaces.org/current/reference/#_jsf_and_cdi_scope_annotations_support) scopes are supported.

- @org.springframework.web.context.annotation.SessionScope
- @org.springframework.context.annotation.Scope("session")
- @javax.faces.bean.SessionScoped (deprecated, do not use for new applications)
- @javax.enterprise.context.SessionScoped
